services:
  # MCP server for Trino
  trino-mcp:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: trino_mcp_trino-mcp_1
    ports:
      - "9096:8000"  # Main MCP SSE port
      - "9097:8001"  # LLM API port with health check endpoint
    volumes:
      - mcp-logs:/app/logs
    environment:
      - PYTHONUNBUFFERED=1
      - TRINO_HOST=host.docker.internal
      - TRINO_PORT=8081
      - LOG_LEVEL=INFO
      - MCP_HOST=0.0.0.0
      - MCP_PORT=8000
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 512M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 20s
      timeout: 5s
      retries: 3
      start_period: 10s
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: ["sh", "-c", "echo 'TRINO_PORT: $TRINO_PORT'; python -m trino_mcp.server --transport sse --host 0.0.0.0 --port 8000 --trino-host $TRINO_HOST --trino-port $TRINO_PORT --trino-catalog $TRINO_CATALOG --trino-user $TRINO_USER --debug"]
    restart: unless-stopped

volumes:
  mcp-logs:
    name: mcp_logs